export enum SCREENS {
  HOME_SCREEN = "HOME",
  DESCRIPTION_SCREEN = "DESCRIPTION",
  LOGIN_SCREEN = "LOGIN",
  REGISTER_SCREEN = "REGISTRATION",
  RESTORATION_SCREEN = "RESTORATION",
  PROFILE_SCREEN = "PROFILE",
}
