export enum SCREENS {
  HOME_SCREEN = "HOME_SCREEN",
  DESCRIPTION_SCREEN = "DESCRIPTION_SCREEN",
  LOGIN_SCREEN = "LOGIN_SCREEN",
  REGISTER_SCREEN = "REGISTER_SCREEN",
  RESTORATION_SCREEN = "RESTORATION_SCREEN",
}
